[package]
name = "ctci_practice_problems"
version = "0.1.0"
authors = ["ali <github@alihong.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
